apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkshelf-server-app-deploy
spec:
  selector:
    matchLabels:
      app: my-bd
  replicas: 3
  template:
    metadata:
      labels:
        app: my-bd
    spec:
      containers:
        - image: afzal442/linkshelf-bd:v1
          name: mybd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MU
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MPW
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MYSECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: my-secret
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-bd
  name: bd-service
spec:
  selector:
    matchLabels:
      app: my-bd
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: None
---

